### ISSUE TITLE
86Box crashes on startup

### ISSUE THREAD

**Issue by dhrdlicka** [OBattler/86Box#210]
Windows 10 v1709 x64, Core i3 4160, integrated graphics.

Stack trace from GDB:
```
(gdb) bt
#0  0x5468a5e6 in igdumdim32!@GTPIN_IGC_PrepareForGTPin@20 ()
   from C:\Windows\SysWOW64\igdumdim32.dll
#1  0x5470c8ab in igdumdim32!@GTPIN_IGC_PrepareForGTPin@20 ()
   from C:\Windows\SysWOW64\igdumdim32.dll
#2  0x5470dc36 in igdumdim32!@GTPIN_IGC_PrepareForGTPin@20 ()
   from C:\Windows\SysWOW64\igdumdim32.dll
#3  0x546dcebb in igdumdim32!@GTPIN_IGC_PrepareForGTPin@20 ()
   from C:\Windows\SysWOW64\igdumdim32.dll
#4  0x6c5093cf in d3d9!Direct3DShaderValidatorCreate9 ()
   from C:\Windows\SYSTEM32\d3d9.dll
#5  0x17ca4d40 in ?? ()
#6  0x6c505d64 in d3d9!Direct3DShaderValidatorCreate9 ()
   from C:\Windows\SYSTEM32\d3d9.dll
#7  0x26bf12dc in ?? ()
#8  0x6c43ae8e in d3d9!Direct3DCreate9Ex () from C:\Windows\SYSTEM32\d3d9.dll
#9  0x6c439778 in d3d9!Direct3DCreate9Ex () from C:\Windows\SYSTEM32\d3d9.dll
#10 0x6c417bfc in d3d9!Direct3DCreate9Ex () from C:\Windows\SYSTEM32\d3d9.dll
#11 0x6c4ab57c in d3d9!DebugSetMute () from C:\Windows\SYSTEM32\d3d9.dll
#12 0x6c4ab407 in d3d9!DebugSetMute () from C:\Windows\SYSTEM32\d3d9.dll
#13 0x006d51f8 in blit_memtoscreen (x=0, y=34, y1=0, y2=208, w=1296, h=208)
    at win/win_d3d.cc:323
#14 0x00630af7 in blit_thread (param=0x0) at video/video.c:203
#15 0x754b6639 in msvcrt!_beginthread () from C:\Windows\System32\msvcrt.dll
#16 0x754b6711 in msvcrt!_endthread () from C:\Windows\System32\msvcrt.dll
#17 0x758e8654 in KERNEL32!BaseThreadInitThunk ()
   from C:\Windows\System32\kernel32.dll
Backtrace stopped: frame did not save the PC
```

**Comment by TC1995** [comment]
That's a problem with the Direct3D renderer iirc.

**Comment by waltje** [comment]
Seems to be fixed by redoing the video resizing.
