### ISSUE TITLE
Segfaulting while changing settings in BIOS

### ISSUE THREAD

**Issue by vmp32k** [OBattler/86Box#233]
I'm getting a SegFault, just as the BIOS is saving my settings and resetting, in: https://github.com/OBattler/86Box/blob/8e6497f01dcf1abe72aea1f317bbba6165e7d026/src/floppy/fdc.c#L1921

```
Thread 18 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 19108.0x2cac]
fdc_reset (priv=0x0) at floppy/fdc.c:1921
1921        default_rwc = (fdc->flags & FDC_FLAG_START_RWC_1) ? 1 : 0;
(gdb) bt
#0  fdc_reset (priv=0x0) at floppy/fdc.c:1921
#1  0x0058d3d0 in um8669f_reset () at sio_um8669f.c:240
#2  0x0041690d in trc_reset (val=6 '\006') at pci.c:654
#3  trc_write (port=3321, val=6 '\006', priv=0x0) at pci.c:679
#4  0x0040f094 in outb (port=3321, val=6 '\006') at io.c:304
#5  0x004cc44f in opOUT_AL_DX (rmdat32=14418115) at cpu/x86_ops_io.h:117
#6  0x004d0da0 in exec386_dynarec (cycs=1333333) at cpu/386_dynarec.c:572
#7  0x00403095 in pc_thread (param=0x19287fc0 <quited>) at pc.c:1007
#8  0x75db6639 in msvcrt!_beginthread () from C:\WINDOWS\System32\msvcrt.dll
#9  0x75db6711 in msvcrt!_endthread () from C:\WINDOWS\System32\msvcrt.dll
#10 0x75c38654 in KERNEL32!BaseThreadInitThunk ()
   from C:\WINDOWS\System32\kernel32.dll
Backtrace stopped: frame did not save the PC
(gdb) info locals
i = 0
default_rwc = <optimized out>
fdc = 0x0
(gdb) info args
priv = 0x0
(gdb) list
1916        int i = 0;
1917        uint8_t default_rwc;
1918
1919        fdc_t *fdc = (fdc_t *) priv;
1920
1921        default_rwc = (fdc->flags & FDC_FLAG_START_RWC_1) ? 1 : 0;
1922
1923        fdc->flags &= ~FDC_FLAG_DISKCHG_ACTLOW;
1924        fdc->enable_3f1 = 1;
1925
```
[Full log up to the crash](https://gist.github.com/vmp32k/ef947c754581b36fdc426d95b83de05e)  
[86box.cfg](https://gist.github.com/vmp32k/591d61af6344f62d42f292f8b20dfa14)

Branch: `master 8e6497f`

**Comment by OBattler** [comment]
This was fixed by yesterday's commit.
